#####################################################################################################
#####                 NSPanel Easy - https://github.com/edwardtfn/NSPanel-Easy                  #####
#####################################################################################################
#### ESPHOME - Page Screensaver                                                                 #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

---
substitutions:
  wakeup_with_button_press: false
  PAGE_SCREENSAVER_ID: 9  # Kept for back compatibility for users using customizations
  TAG_PAGE_SCREENSAVER: nspanel.page.screensaver

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_EASY_PAGE_SCREENSAVER

globals:
  - id: screensaver_background_color
    type: uint16_t
    restore_value: true
    initial_value: 'Colors::RGB565_BLACK'
  - id: screensaver_display_time
    type: bool
    restore_value: true
    initial_value: 'false'
  - id: screensaver_display_time_font
    type: uint8_t
    restore_value: true
    initial_value: '6'
  - id: screensaver_display_time_color
    type: uint16_t
    restore_value: true
    initial_value: 'Colors::RGB565_GRAY_DARK'

number:
  - id: display_sleep_brightness  # Screen brightness when in screensaver page
    name: Display Brightness Sleep
    platform: template
    entity_category: config
    unit_of_measurement: '%'
    min_value: 0
    max_value: 100
    initial_value: 0
    step: 1
    restore_value: true
    optimistic: true
    update_interval: never
    on_value:
      then:
        - lambda: |-
            disp1->send_command_printf("brightness_sleep=%i", int(x));
            page_screensaver_apply_settings->execute();

  - name: Timeout Sleep
    platform: template
    id: timeout_sleep
    entity_category: config
    min_value: 0
    max_value: 86400
    initial_value: 60
    step: 1
    restore_value: true
    optimistic: true
    icon: mdi:timer
    unit_of_measurement: "s"
    update_interval: never
    on_value:
      then:
        - lambda: |-
            if (x == 0 and current_page_id == get_page_id("screensaver")) {
              wakeup->execute(false);
            }
            timer_sleep->execute();

script:
  - id: !extend action_component_color
    then:
      - lambda: |-
          if (page != "mem") return;
          if (component == hmi::screensaver::TEXT.name) {
            id(screensaver_display_time_color) = color;
            disp1->send_command_printf("screensaver_pco=%" PRIu16, id(screensaver_display_time_color));
            page_screensaver_apply_settings->execute();
            return;
          }
          if (component == "screensaver_bco" and id(screensaver_background_color) != color) {
            id(screensaver_background_color) = color;
            disp1->send_command_printf("screensaver_bco=%" PRIu16, id(screensaver_background_color));
            page_screensaver_apply_settings->execute();
            return;
          }

  - id: !extend action_component_val
    then:
      - lambda: |-
          if (page != "mem") return;
          if (component == "screensaver_display_time") {
            const bool temp_display_time = (val > 0);
            if (id(screensaver_display_time) != temp_display_time) {
              id(screensaver_display_time) = temp_display_time;
              if (id(screensaver_display_time)) refresh_datetime->execute();
            }
            return;
          }
          if (component == "screensaver_time_font" and id(screensaver_display_time_font) != val) {
            id(screensaver_display_time_font) = val;
            disp1->send_command_printf("screensaver_font=%" PRIu16, id(screensaver_display_time_font));
            page_screensaver_apply_settings->execute();
            return;
          }

  - id: !extend ha_button
    then:
      - lambda: |-
          if (current_page_id != get_page_id("screensaver")) {
            timer_reset_all->execute();
            return;
          }
          ESP_LOGV("${TAG_PAGE_SCREENSAVER}", "wakeup_with_button_press: ${wakeup_with_button_press}");
          if (${wakeup_with_button_press | lower}) {
            wakeup->execute(true);
          }

  - id: !extend boot_nextion
    then:
      - lambda: |-
          disp1->send_command_printf("screensaver_bco=%" PRIu16, id(screensaver_background_color));
          disp1->send_command_printf("screensaver_font=%" PRIu16, id(screensaver_display_time_font));
          disp1->send_command_printf("screensaver_pco=%" PRIu16, id(screensaver_display_time_color));
          disp1->send_command_printf("brightness_sleep=%i", int(display_sleep_brightness->state));
          page_screensaver_apply_settings->execute();

  - id: !extend page_change
    then:
      - lambda: |-
          if (new_page_id == get_page_id("screensaver")) page_screensaver->execute();

  - id: page_screensaver
    mode: restart
    then:
      - lambda: |-
          if (current_page_id != get_page_id("screensaver")) return;
          page_screensaver_apply_settings->execute();
          refresh_hardware_buttons_bars->execute(3);
          if (id(screensaver_display_time)) refresh_datetime->execute();
          page_screensaver_apply_settings_with_delay->execute();

  - id: page_screensaver_apply_settings
    then:
      - lambda: |-
          if (current_page_id != get_page_id("screensaver")) return;
          disp1->send_command("apply_settings.en=1");

  - id: page_screensaver_apply_settings_with_delay
    mode: restart
    then:
      - delay: 5s
      - script.execute: page_screensaver_apply_settings

  - id: !extend stop_all
    then:
      - lambda: |-
          page_screensaver->stop();
          page_screensaver_apply_settings->stop();
          page_screensaver_apply_settings_with_delay->stop();
          timer_sleep->stop();

  - id: timer_sleep      # Handles the sleep (go to screensaver page) after a timeout
    mode: restart
    then:
      - if:
          condition:
            - lambda: return timeout_sleep->state > 0;
          then:
            - delay: !lambda return (int(timeout_sleep->state) *1000);
            - lambda: |-
                if (timeout_sleep->state <= 0) return;                      // Sleep is disabled
                if (current_page_id == get_page_id("screensaver")) return;  // Already sleeping
                if (current_page_id == get_page_id("boot")) return;         // Don't sleep during boot
                ESP_LOGD("${TAG_PAGE_SCREENSAVER}", "Sleep from '%s'", page_names[current_page_id]);
                goto_page->execute(get_page_id("screensaver"));

  - id: !extend timer_reset_all
    then:
      - script.execute: timer_sleep

  - id: !extend watchdog_round
    then:
      - lambda: |-
          if (current_page_id != get_page_id("screensaver")) return;
          disp1->send_command("dim=brightness_sleep");
...
