#####################################################################################################
#####                 NSPanel Easy - https://github.com/edwardtfn/NSPanel-Easy                  #####
######################################################################################################
#### ESPHOME CORE - Page weather                                                               #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################
---
substitutions:
  PAGE_WEATHER01_ID: 2
  PAGE_WEATHER02_ID: 3
  PAGE_WEATHER03_ID: 4
  PAGE_WEATHER04_ID: 5
  PAGE_WEATHER05_ID: 6
  TAG_PAGE_WEATHER: nspanel.page.weather
  SECONDS_PER_DAY: 86400

display:
  - id: !extend disp1
    on_touch:
      then:
        - lambda: |-
            if (touch_event) return;  // Ignore the touch, so only the release will be used
            if (page_id == hmi::home::PAGE.id and               // Page `home`
                system_flags.api_ready and                      // Is API available?
                (component_id == hmi::home::WEATHER.id or       // Outdoor temperature
                component_id == hmi::home::OUTDOOR_TEMP.id)) {  // Weather picture
              goto_page->execute(${PAGE_WEATHER01_ID});
              return;
            }

globals:
  - id: weather_icon
    type: uint8_t
    restore_value: false
    initial_value: '0'

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_EASY_PAGE_WEATHER

script:
  - id: !extend action_component_val
    then:
      - lambda: |-
          if (page != "mem") return;
          if (component == "weather_icon") {
            id(weather_icon) = static_cast<uint8_t>(val);
            theme_update_all_weather_icon->execute();
          }

  - id: !extend page_change
    then:
      - lambda: |-
          if (new_page_id >= ${PAGE_WEATHER01_ID} and new_page_id <= ${PAGE_WEATHER05_ID})
            page_weather->execute();

  - id: page_weather
    mode: restart
    then:
      - lambda: |-
          const uint8_t page_index = current_page_id - ${PAGE_WEATHER01_ID};
          if (page_index >= 5) {
            ESP_LOGW("${TAG_PAGE_WEATHER}", "Unexpected page_index: %" PRIu8, page_index);
            return;
          }
          const uint32_t timestamp = id(time_provider).now().timestamp + (page_index * ${SECONDS_PER_DAY});

          static const char* const relative_days[5] = {
            "${LOCALIZATION[LANG].relative_day.today}",
            "${LOCALIZATION[LANG].relative_day.tomorrow}",
            "${LOCALIZATION[LANG].relative_day.in_2_days}",
            "${LOCALIZATION[LANG].relative_day.in_3_days}",
            "${LOCALIZATION[LANG].relative_day.in_4_days}"
          };

          disp1->set_component_text("day", relative_days[page_index]);
          render_date->execute("date", timestamp);

  - id: !extend stop_page_constructors
    then:
      - lambda: page_weather->stop();

  - id: !extend stop_all
    then:
      - lambda: theme_update_all_weather_icon->stop();

  - id: !extend theme_update_all
    then:
      - script.execute: theme_update_all_weather_icon
      - script.wait: theme_update_all_weather_icon

  - id: theme_update_all_weather_icon
    then:
      - lambda: |-
          if ( current_page_id >= ${PAGE_WEATHER01_ID} and current_page_id <= ${PAGE_WEATHER05_ID}) {
            const uint8_t weather_icon_corrected = id(weather_icon) +
                                ((current_theme == ThemeMode::LIGHT) ? ${THEME_DARK_PIC_PAGE_HOME_WEATHER_OFFSET} : 0);
            ESP_LOGD("${TAG_PAGE_HOME}", "Update weather icon: %" PRIu8, weather_icon_corrected);
            disp1->set_component_pic("weather_icon", weather_icon_corrected);
          }
...
