#####################################################################################################
#####                 NSPanel Easy - https://github.com/edwardtfn/NSPanel-Easy                  #####
#####################################################################################################
##### ESPHOME STANDARD                                                                          #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################
---
substitutions:
  TAG_STANDARD: nspanel.standard

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_EASY_STANDARD

packages:
  # yamllint disable rule:colons
  - !include nspanel_esphome_hw_buzzer.yaml
  - !include nspanel_esphome_hw_relays.yaml
  - !include nspanel_esphome_hw_temperature.yaml
  - !include nspanel_esphome_page_alarm.yaml
  - !include nspanel_esphome_page_button.yaml
  - !include nspanel_esphome_page_buttons.yaml
  - !include nspanel_esphome_page_canvas.yaml
  - !include nspanel_esphome_page_climate.yaml
  - !include nspanel_esphome_page_confirm.yaml
  - !include nspanel_esphome_page_cover.yaml
  - !include nspanel_esphome_page_entities.yaml
  - !include nspanel_esphome_page_fan.yaml
  - !include nspanel_esphome_page_keyb_num.yaml
  - !include nspanel_esphome_page_light.yaml
  - !include nspanel_esphome_page_media_player.yaml
  - !include nspanel_esphome_page_notification.yaml
  - !include nspanel_esphome_page_qrcode.yaml
  - !include nspanel_esphome_page_settings.yaml
  - !include nspanel_esphome_page_switch.yaml
  - !include nspanel_esphome_page_utilities.yaml
  - !include nspanel_esphome_page_water_heater.yaml
  - !include nspanel_esphome_page_weather.yaml
  # yamllint enable rule:colons
...
