#####################################################################################################
#####                 NSPanel Easy - https://github.com/edwardtfn/NSPanel-Easy                  #####
#####################################################################################################
##### ESPHOME - Page Confirm                                                                    #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################

---
substitutions:
  BOOT_STEP_PAGE_CONFIRM: 13
  PAGE_CONFIRM_ID: 26
  TAG_PAGE_CONFIRM: nspanel.page.confirm

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_EASY_PAGE_CONFIRM

script:
  - id: !extend page_change
    then:
      - lambda: |-
          if (new_page_id == ${PAGE_CONFIRM_ID})
            page_confirm->execute();

  - id: page_confirm
    mode: single
    then:
      - lambda: |-
          if (current_page_id != ${PAGE_CONFIRM_ID}) return;
          if (!is_device_ready_for_tasks()) return;
          disp1->set_component_text("confirm.title", wrapText(
                                                                "${LOCALIZATION[LANG].please_confirm}",
                                                                15,
                                                                ${LANG_BYTES_PER_CHAR}
                                                              ).c_str()
                                    );

  - id: !extend stop_page_constructors
    then:
      - lambda: page_confirm->stop();

...
