---
name: Validate Python (flake8)

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - "**/*.py"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v6.0.2

      - name: Set up Python environment
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.11"

      - name: Install flake8
        run: pip install flake8

      - name: flake8 Lint
        run: flake8 --max-line-length=200 components/nspanel_easy
...
